#!/bin/bash

# setup thingsboards data and logs dirs
mkdir -p ~/.mytb-data && sudo chown -R 799:799 ~/.mytb-data
mkdir -p ~/.mytb-logs && sudo chown -R 799:799 ~/.mytb-logs

# setup iotgw conf dir
mkdir -p ~/.tb-gateway/config

cp tb-gateway-conf/* ~/.tb-gateway/config